name: media_cache_manager_example
description: Demonstrates how to use the media_cache_manager plugin.

publish_to: 'none'

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  media_cache_manager:
    path: ../

  cupertino_icons: ^1.0.5
  better_player: ^0.0.83

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true