name: media_cache_manager
description: This package helps you to cache media (Audio, Video, Image, etc...).
version: 0.1.0
homepage: https://github.com/AhmedAbogameel/media_cache_manager
repository: https://github.com/AhmedAbogameel/media_cache_manager

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:

  path_provider: ^2.0.15
  dio: ^5.1.2
  get_storage: ^2.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0