name: media_cache_manager
description: This package helps you to cache media (Audio, Video, Image, etc...).
version: 0.3.0
homepage: https://github.com/AhmedAbogameel/media_cache_manager
repository: https://github.com/AhmedAbogameel/media_cache_manager

environment:
  sdk: ^3.5.2

dependencies:

  path_provider: ^2.1.5
  dio: ^5.7.0
  get_storage: ^2.1.1
  aes_crypt_null_safe: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0